(() => {
  const BRIDGE_SOURCE = "anti-ai-page-hook";
  const STORAGE_KEYS = {
    enabled: "antiAIEnabled",
    mode: "antiAIMode",
    sensitivity: "antiAISensitivity",
    hideAiOverview: "antiAIHideAiOverview",
    stats: "antiAIStats",
    blockedChannels: "antiAIBlockedChannels"
  };

  const DEFAULT_SETTINGS = {
    antiAIEnabled: true,
    antiAIMode: "remove",
    antiAISensitivity: "normal",
    antiAIHideAiOverview: true
  };

  const STRONG_KEYWORDS = [
    "ai generated",
    "ai-generated",
    "a.i. generated",
    "generated by ai",
    "made with ai",
    "created with ai",
    "generated with ai",
    "ai art",
    "ai image",
    "ai video",
    "ai girls",
    "synthetic media",
    "midjourney",
    "stable diffusion",
    "dall-e",
    "dalle",
    "dall·e",
    "runwayml",
    "runway ml",
    "runway gen",
    "sora",
    "flux",
    "ideogram",
    "leonardo ai",
    "adobe firefly",
    "dream machine",
    "luma ai",
    "comfyui",
    "invoke ai",
    "generated via prompt",
    "prompt used",
    "text to image",
    "text to video",
    "image to video"
  ];

  const WEAK_KEYWORDS = [
    "#aiart",
    "#aivideo",
    "#aiimage",
    "#ai",
    "#shorts",
    "#short",
    "#generativeai",
    "#genai",
    "#midjourney",
    "#stablediffusion",
    "#dalle",
    "#sora",
    "#runway",
    "#leonardoai",
    "#adobefirefly",
    "#syntheticmedia",
    "#madewithai",
    "#madewithai",
    "prompt:",
    "prompt by",
    "generated in",
    "rendered in",
    "upscaled with",
    "lora",
    "seed:"
  ];

  const URL_HINTS = [
    "midjourney",
    "stablediffusion",
    "dalle",
    "openai",
    "sora",
    "runway",
    "firefly",
    "leonardo",
    "genai",
    "ai_generated",
    "ai-generated",
    "generated-by-ai"
  ];

  const METADATA_TEXT_SELECTORS = [
    "[title]",
    "[aria-label]",
    "a",
    "h1",
    "h2",
    "h3",
    "h4",
    "yt-formatted-string",
    "#video-title",
    "#video-title-link",
    "#snippet-text",
    "#channel-name",
    "#content-text"
  ];

  const MEDIA_SELECTOR = "img, video";
  const POST_SELECTORS = [
    "article",
    'div[role="article"]',
    '[data-testid="tweet"]',
    '[data-testid="cellInnerDiv"]',
    "shreddit-post",
    '[data-ad-preview="message"]',
    '[data-pagelet^="FeedUnit_"]',
    '[data-pagelet^="ProfileTimeline"]',
    '[data-e2e="recommend-list-item-container"]',
    '[data-e2e="search_top-item"]',
    "ytd-video-renderer",
    "ytd-rich-item-renderer",
    "ytd-grid-video-renderer",
    "ytd-compact-video-renderer",
    "ytd-reel-shelf-renderer",
    "ytd-reel-item-renderer",
    "ytd-playlist-renderer"
  ];

  const POST_MEDIA_HINT_SELECTORS = [
    MEDIA_SELECTOR,
    'a[href*="/status/"]',
    'a[href*="/reel/"]',
    'a[href*="/video/"]',
    'a[href*="/watch?v="]',
    'a[href^="/shorts/"]'
  ];
  const YOUTUBE_LINK_SELECTORS = ['a[href*="/watch?v="]', 'a[href^="/shorts/"]'];
  const YOUTUBE_CARD_SELECTORS = [
    "ytd-video-renderer",
    "ytd-rich-item-renderer",
    "ytd-grid-video-renderer",
    "ytd-compact-video-renderer",
    "ytd-rich-shelf-renderer",
    "ytd-reel-item-renderer",
    "ytd-playlist-renderer",
    "yt-lockup-view-model",
    "ytd-shorts-lockup-view-model",
    "ytm-shorts-lockup-view-model-v2",
    "ytm-shorts-lockup-view-model",
    ".ytGridShelfViewModelGridShelfItem"
  ];
  const YOUTUBE_SHORTS_TARGET_SELECTORS = [
    ".ytGridShelfViewModelGridShelfItem",
    "ytm-shorts-lockup-view-model-v2",
    "ytm-shorts-lockup-view-model",
    "ytd-reel-video-renderer",
    "ytm-reel-item-renderer",
    "ytm-shorts-player-item-renderer",
    "ytd-reel-item-renderer",
    "yt-lockup-view-model",
    "ytd-shorts-lockup-view-model",
    "ytd-rich-item-renderer"
  ];
  const YOUTUBE_SHORTS_WATCH_SELECTORS = [
    "ytd-reel-video-renderer",
    "ytd-shorts",
    "ytm-reel-item-renderer",
    "ytm-shorts-player-item-renderer",
    "ytd-reel-item-renderer"
  ];
  const REDDIT_CARD_SELECTORS = [
    "shreddit-post",
    'article[data-testid="post-container"]',
    "faceplate-tracker"
  ];
  const REDDIT_POST_ATTRIBUTES = [
    "post-title",
    "content-href",
    "permalink",
    "post-type",
    "domain",
    "subreddit-prefixed-name",
    "author",
    "comment-count",
    "score",
    "aria-label",
    "title"
  ];

  const BLOCK_CLASS = "anti-ai-blocked";
  const BLUR_CLASS = "anti-ai-blurred";
  const BADGE_CLASS = "anti-ai-badge";
  const CHANNEL_BLOCK_BUTTON_CLASS = "anti-ai-channel-block";
  const PROCESSED_ATTR = "data-anti-ai-processed";
  const SCORE_ATTR = "data-anti-ai-score";
  const REASON_ATTR = "data-anti-ai-reasons";
  const HIDDEN_ATTR = "data-anti-ai-hidden";
  const SKIPPED_ATTR = "data-anti-ai-skipped";
  const REVEALED_ATTR = "data-anti-ai-revealed";

  let settings = { ...DEFAULT_SETTINGS };
  let scanTimer = null;
  let observer = null;
  let isStopped = false;
  const youtubeMetadataByVideoId = new Map();
  const blockedChannels = new Map();
  let lastShortSkip = {
    videoId: "",
    at: 0
  };
  let stats = {
    hostname: location.hostname,
    hidden: 0,
    mode: DEFAULT_SETTINGS.antiAIMode,
    updatedAt: Date.now()
  };

  function stopProcessing() {
    isStopped = true;
    if (scanTimer !== null) {
      window.clearTimeout(scanTimer);
      scanTimer = null;
    }
    if (observer) {
      observer.disconnect();
      observer = null;
    }
  }

  function isExtensionContextError(error) {
    return /extension context invalidated/i.test(String(error?.message || error || ""));
  }

  function guardExecution(fn, fallbackValue) {
    if (isStopped) return fallbackValue;
    try {
      return fn();
    } catch (error) {
      if (isExtensionContextError(error)) {
        stopProcessing();
        return fallbackValue;
      }
      throw error;
    }
  }

  function hasValidExtensionContext() {
    try {
      return Boolean(globalThis.chrome?.runtime?.id && globalThis.chrome?.storage);
    } catch {
      return false;
    }
  }

  function safeStorageLocalSet(value) {
    if (!hasValidExtensionContext()) return;
    try {
      chrome.storage.local.set(value);
    } catch (error) {
      if (isExtensionContextError(error)) {
        stopProcessing();
      }
    }
  }

  function safeStorageSyncGet(defaults, callback) {
    if (!hasValidExtensionContext()) {
      callback(defaults);
      return;
    }

    try {
      chrome.storage.sync.get(defaults, (items) => {
        const runtimeError = chrome.runtime?.lastError;
        if (runtimeError) {
          if (isExtensionContextError(runtimeError)) {
            stopProcessing();
          }
          callback(defaults);
          return;
        }
        callback(items);
      });
    } catch (error) {
      if (isExtensionContextError(error)) {
        stopProcessing();
      }
      callback(defaults);
    }
  }

  function safeStorageSyncSet(value) {
    if (!hasValidExtensionContext()) return;
    try {
      chrome.storage.sync.set(value);
    } catch (error) {
      if (isExtensionContextError(error)) {
        stopProcessing();
      }
    }
  }

  function safeBindStorageChanges(listener) {
    if (!hasValidExtensionContext()) return;
    try {
      chrome.storage.onChanged.addListener(listener);
    } catch (error) {
      if (isExtensionContextError(error)) {
        stopProcessing();
      }
    }
  }

  function installStyles() {
    if (document.getElementById("anti-ai-style")) return;
    const style = document.createElement("style");
    style.id = "anti-ai-style";
    style.textContent = `
      .${BLOCK_CLASS} {
        display: none !important;
      }

      .${BLUR_CLASS} {
        position: relative !important;
        overflow: hidden !important;
      }

      .${BLUR_CLASS} > *:not(.${BADGE_CLASS}) {
        filter: blur(18px) saturate(0.65) !important;
        pointer-events: none !important;
        user-select: none !important;
      }

      .${BADGE_CLASS} {
        position: absolute;
        top: 12px;
        right: 12px;
        z-index: 2147483647;
        display: inline-flex;
        align-items: center;
        gap: 8px;
        max-width: min(320px, calc(100% - 24px));
        padding: 8px 12px;
        border-radius: 999px;
        background: rgba(11, 16, 20, 0.92);
        color: #f6f7f8;
        font: 600 12px/1.2 Arial, sans-serif;
        letter-spacing: 0.01em;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.24);
      }

      .${BADGE_CLASS} button {
        border: 0;
        border-radius: 999px;
        padding: 4px 9px;
        background: #f6f7f8;
        color: #11161a;
        font: inherit;
        cursor: pointer;
      }

      .${CHANNEL_BLOCK_BUTTON_CLASS} {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        margin-left: 8px;
        padding: 4px 8px;
        border: 1px solid rgba(255, 255, 255, 0.18);
        border-radius: 999px;
        background: rgba(11, 16, 20, 0.84);
        color: #f6f7f8;
        font: 600 11px/1 Arial, sans-serif;
        cursor: pointer;
        vertical-align: middle;
      }

      .${CHANNEL_BLOCK_BUTTON_CLASS}:hover {
        background: rgba(26, 33, 39, 0.96);
      }
    `;
    document.documentElement.appendChild(style);
  }

  function normalizeText(value) {
    return String(value || "")
      .toLowerCase()
      .replace(/[\u2010-\u2015]/g, "-")
      .replace(/[#]+/g, " #")
      .replace(/[_-]+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function normalizeKeyword(value) {
    return normalizeText(value);
  }

  function getThreshold() {
    return settings.antiAISensitivity === "strict" ? 2 : 4;
  }

  function isYouTubeHost() {
    return /(^|\.)youtube\.com$/i.test(location.hostname);
  }

  function isTwitterHost() {
    return /(^|\.)((x|twitter)\.com)$/i.test(location.hostname);
  }

  function isGoogleHost() {
    return /(^|\.)google\.com$/i.test(location.hostname);
  }

  function isGoogleSearchPage() {
    return isGoogleHost() && /^\/search(?:\/|$)?/i.test(location.pathname);
  }

  function isBingSearchPage() {
    return /(^|\.)bing\.com$/i.test(location.hostname) && /^\/search(?:\/|$)?/i.test(location.pathname);
  }

  function isYandexSearchPage() {
    return /(^|\.)yandex\.(com|ru)$/i.test(location.hostname) && /^\/search(?:\/|$)?/i.test(location.pathname);
  }

  function isBraveSearchPage() {
    return /^search\.brave\.com$/i.test(location.hostname) && /^\/search(?:\/|$)?/i.test(location.pathname);
  }

  function isDuckDuckGoSearchPage() {
    return /(^|\.)duckduckgo\.com$/i.test(location.hostname) && /^\/?$/i.test(location.pathname);
  }

  function isYouTubeShortsPage() {
    return isYouTubeHost() && /^\/shorts(\/|$)/i.test(location.pathname);
  }

  function extractYouTubeVideoIdFromUrl(rawUrl) {
    if (!rawUrl) return "";

    try {
      const url = new URL(rawUrl, location.origin);
      if (/^\/shorts\//i.test(url.pathname)) {
        return url.pathname.split("/").filter(Boolean)[1] || "";
      }

      if (/^\/watch/i.test(url.pathname)) {
        return url.searchParams.get("v") || "";
      }
    } catch {
      return "";
    }

    return "";
  }

  function getYouTubeVideoIdsForPost(post) {
    const ids = new Set();

    if (isYouTubeShortsPage()) {
      const currentId = extractYouTubeVideoIdFromUrl(location.href);
      if (currentId) ids.add(currentId);
    }

    const links = guardExecution(
      () => post.querySelectorAll('a[href*="/watch?v="], a[href^="/shorts/"]'),
      []
    );

    for (const link of links) {
      if (!(link instanceof HTMLAnchorElement)) continue;
      const id = extractYouTubeVideoIdFromUrl(link.href);
      if (id) ids.add(id);
    }

    const selfId =
      extractYouTubeVideoIdFromUrl(post.getAttribute("href") || "") ||
      extractYouTubeVideoIdFromUrl(post.getAttribute("content-url") || "");
    if (selfId) ids.add(selfId);

    return Array.from(ids);
  }

  function extractYouTubeChannelInfo(post) {
    if (!isYouTubeHost() || !(post instanceof HTMLElement)) return null;

    const channelLinkSelectors = [
      'a[href^="/@"]',
      'a[href^="/channel/"]',
      'a[href^="/c/"]',
      'a[href^="/user/"]'
    ];
    const selectors = channelLinkSelectors.join(", ");
    const links = guardExecution(() => post.querySelectorAll(selectors), []);

    for (const link of links) {
      if (!(link instanceof HTMLAnchorElement)) continue;
      const href = link.getAttribute("href") || "";
      const label = normalizeText(link.textContent || link.getAttribute("aria-label") || "");
      const key = normalizeText(href);
      if (!key) continue;
      return {
        key,
        label: label || key,
        href
      };
    }

    const channelNameNode = guardExecution(
      () =>
        post.querySelector(
          "#channel-name, ytd-channel-name, .shortsLockupViewModelHostChannelName, .yt-core-attributed-string"
        ),
      null
    );

    if (channelNameNode instanceof HTMLElement) {
      const label = normalizeText(channelNameNode.textContent || "");
      if (label) {
        return {
          key: `name:${label}`,
          label,
          href: ""
        };
      }
    }

    return null;
  }

  function getYouTubeNetworkMetadata(post) {
    if (!isYouTubeHost()) return "";

    const ids = getYouTubeVideoIdsForPost(post);
    if (!ids.length) return "";

    const textParts = [];
    for (const id of ids) {
      const value = youtubeMetadataByVideoId.get(id);
      if (!value) continue;
      textParts.push(value);
    }

    return textParts.join(" \n ");
  }

  function getCurrentYouTubeShortId() {
    return isYouTubeShortsPage() ? extractYouTubeVideoIdFromUrl(location.href) : "";
  }

  function pauseMediaWithin(target) {
    const mediaNodes = guardExecution(() => target.querySelectorAll("video, audio"), []);
    for (const media of mediaNodes) {
      if (
        media instanceof HTMLMediaElement &&
        typeof media.pause === "function" &&
        !media.paused
      ) {
        try {
          media.pause();
        } catch {
          // Ignore media pause failures.
        }
      }
    }
  }

  function advanceYouTubeShort() {
    const activeElement =
      document.activeElement instanceof HTMLElement ? document.activeElement : document.body;

    const keydown = new KeyboardEvent("keydown", {
      key: "ArrowDown",
      code: "ArrowDown",
      keyCode: 40,
      which: 40,
      bubbles: true
    });
    const keyup = new KeyboardEvent("keyup", {
      key: "ArrowDown",
      code: "ArrowDown",
      keyCode: 40,
      which: 40,
      bubbles: true
    });

    activeElement.dispatchEvent(keydown);
    document.dispatchEvent(keydown);
    window.dispatchEvent(keydown);

    window.setTimeout(() => {
      activeElement.dispatchEvent(keyup);
      document.dispatchEvent(keyup);
      window.dispatchEvent(keyup);
    }, 30);
  }

  function skipYouTubeShort(target) {
    if (!isYouTubeShortsPage()) return false;

    const currentVideoId = getCurrentYouTubeShortId();
    const now = Date.now();
    if (
      currentVideoId &&
      lastShortSkip.videoId === currentVideoId &&
      now - lastShortSkip.at < 1200
    ) {
      return true;
    }

    pauseMediaWithin(target);
    target.setAttribute(SKIPPED_ATTR, "1");
    lastShortSkip = {
      videoId: currentVideoId,
      at: now
    };
    advanceYouTubeShort();
    return true;
  }

  function isBlockedChannel(post) {
    const info = extractYouTubeChannelInfo(post);
    if (!info?.key) return null;
    return blockedChannels.get(info.key) || null;
  }

  function isRedditHost() {
    return /(^|\.)reddit\.com$/i.test(location.hostname);
  }

  function hideMatchedContainers(selectors, options = {}) {
    const removed = new Set();
    for (const selector of selectors) {
      const nodes = guardExecution(() => document.querySelectorAll(selector), []);
      for (const node of nodes) {
        if (!(node instanceof HTMLElement)) continue;
        const target =
          (typeof options.closest === "string" && node.closest(options.closest)) || node;
        if (!(target instanceof HTMLElement)) continue;
        if (removed.has(target)) continue;
        target.style.display = "none";
        target.setAttribute("data-anti-ai-overview-hidden", "1");
        removed.add(target);
      }
    }

    return removed.size;
  }

  function removeGoogleAiOverview() {
    if (!isGoogleSearchPage() || !settings.antiAIHideAiOverview) return 0;

    return hideMatchedContainers(
      [
        "[jscontroller='qTdDb']",
        "[data-attrid='ai_overview']",
        "[data-attrid='overview']",
        "[aria-label='AI Overview']",
        "[aria-label='AI overview']",
        "#eKIzJc",
        ".Wm5I1e[jsname='ZLxsqf'][data-tma]",
        ".EyBRub.jUja0e",
        ".YzCcne[data-mcp]"
      ],
      {
        closest: ".ULSxyf, #rso > div, #search .MjjYud, #search .g, [data-snc]"
      }
    );
  }

  function removeBingAiOverview() {
    if (!isBingSearchPage() || !settings.antiAIHideAiOverview) return 0;

    const removed =
      hideMatchedContainers(
      [
        "[data-testid*='copilot']",
        "[aria-label='Copilot answer']",
        "[aria-label='Copilot Answer']",
        "[aria-label='Copilot Search']",
        "[aria-label='copilot search']",
        "#b_context [class*='copilot']",
        "#b_topw [class*='copilot']",
        "#b_topw [id*='copilot']",
        "#b_results [class*='copilot']"
      ],
      {
        closest: "#b_results > li, #b_context > li, #b_topw > div, .b_ans"
      }
    );

    const candidates = guardExecution(
      () => document.querySelectorAll("#b_topw > div, #b_context > li, #b_results > li.b_ans"),
      []
    );

    for (const node of candidates) {
      if (!(node instanceof HTMLElement)) continue;
      if (node.getAttribute("data-anti-ai-overview-hidden") === "1") continue;

      const text = normalizeText(node.innerText || node.textContent || "");
      if (!text) continue;
      const looksLikeCopilotModule =
        text.includes("copilot search") ||
        text.includes("copilot answer") ||
        text.includes("search with copilot") ||
        text.includes("answer from copilot");
      if (!looksLikeCopilotModule) continue;

      node.style.display = "none";
      node.setAttribute("data-anti-ai-overview-hidden", "1");
      removed.add(node);
    }

    return removed.size;
  }

  function removeYandexAiOverview() {
    if (!isYandexSearchPage() || !settings.antiAIHideAiOverview) return 0;

    return hideMatchedContainers(
      [
        "[data-testid*='neuro']",
        "[data-baobab-name*='Neuro']",
        "[data-log-node*='neuro']",
        "[aria-label='Нейро']",
        "[aria-label='Yandex Neuro']"
      ],
      {
        closest: "#search-result > li, .serp-item, .main__result, .organic"
      }
    );
  }

  function removeBraveAiOverview() {
    if (!isBraveSearchPage() || !settings.antiAIHideAiOverview) return 0;

    return hideMatchedContainers(
      [
        "search-ai-answer",
        "[data-type='summarizer']",
        "[data-test-id='ai-answer']",
        "[class*='summarizer']"
      ],
      {
        closest: "search-serp-module, .snippet, .card, .box"
      }
    );
  }

  function removeDuckDuckGoAiOverview() {
    if (!isDuckDuckGoSearchPage() || !settings.antiAIHideAiOverview) return 0;

    return hideMatchedContainers(
      [
        "[data-testid='ai-answer']",
        "[data-testid='search-assist']",
        "[data-layout='ai_assisted_answer']",
        "[data-layout='search_assist']",
        "[aria-label='AI-assisted answer']",
        "[aria-label='Search Assist']"
      ],
      {
        closest: "[data-testid='mainline'] > div, .results--main > *"
      }
    );
  }

  function removeSearchEngineAiOverviews() {
    return (
      removeGoogleAiOverview() +
      removeBingAiOverview() +
      removeYandexAiOverview() +
      removeBraveAiOverview() +
      removeDuckDuckGoAiOverview()
    );
  }

  function getBlockTarget(post) {
    if (!(post instanceof HTMLElement)) return null;

    if (isYouTubeHost()) {
      const shortsLink = post.matches('a[href^="/shorts/"]')
        ? post
        : post.querySelector('a[href^="/shorts/"]');
      if (shortsLink instanceof HTMLElement) {
        const shortsTarget = shortsLink.closest(YOUTUBE_SHORTS_TARGET_SELECTORS.join(", "));
        if (shortsTarget instanceof HTMLElement) return shortsTarget;
      }

      if (isYouTubeShortsPage()) {
        const shortsWatchTarget = post.closest(YOUTUBE_SHORTS_WATCH_SELECTORS.join(", "));
        if (shortsWatchTarget instanceof HTMLElement) return shortsWatchTarget;
      }

      const youtubeTarget = post.closest(YOUTUBE_CARD_SELECTORS.join(", "));
      if (youtubeTarget instanceof HTMLElement) return youtubeTarget;
    }

    if (isTwitterHost()) {
      const twitterTarget = post.closest('[data-testid="tweet"], article[role="article"]');
      if (twitterTarget instanceof HTMLElement) return twitterTarget;
    }

    if (isRedditHost()) {
      const redditTarget = post.closest(REDDIT_CARD_SELECTORS.join(", "));
      if (redditTarget instanceof HTMLElement) return redditTarget;
    }

    return post;
  }

  function collectYouTubeCandidates() {
    const seen = new Set();
    const posts = [];

    if (isYouTubeShortsPage()) {
      const shortsNodes = guardExecution(
        () => document.querySelectorAll(YOUTUBE_SHORTS_WATCH_SELECTORS.join(", ")),
        []
      );

      for (const node of shortsNodes) {
        if (!(node instanceof HTMLElement)) continue;
        const card = getBlockTarget(node);
        if (!(card instanceof HTMLElement)) continue;
        if (seen.has(card)) continue;
        seen.add(card);
        posts.push(card);
      }

      if (posts.length) {
        return posts;
      }
    }

    const linkSelector = YOUTUBE_LINK_SELECTORS.join(", ");
    const cardSelector = YOUTUBE_CARD_SELECTORS.join(", ");
    const links = guardExecution(() => document.querySelectorAll(linkSelector), []);

    for (const link of links) {
      if (!(link instanceof HTMLElement)) continue;
      const shortsCard = link.matches('a[href^="/shorts/"]')
        ? link.closest(YOUTUBE_SHORTS_TARGET_SELECTORS.join(", "))
        : null;
      const card = shortsCard || link.closest(cardSelector);
      if (!(card instanceof HTMLElement)) continue;
      if (seen.has(card)) continue;
      seen.add(card);
      posts.push(card);
    }

    return posts;
  }

  function isRedditCandidate(node) {
    if (!(node instanceof HTMLElement)) return false;

    if (node.tagName.toLowerCase() === "shreddit-post") {
      const postType = normalizeText(node.getAttribute("post-type"));
      if (["image", "video", "gallery", "link"].includes(postType)) {
        return true;
      }
      if (node.getAttribute("content-href") || node.getAttribute("post-title")) {
        return true;
      }
    }

    return Boolean(
      node.querySelector(MEDIA_SELECTOR) ||
        node.querySelector('a[href*="/comments/"]') ||
        node.querySelector("shreddit-post")
    );
  }

  function collectRedditCandidates() {
    const seen = new Set();
    const posts = [];
    const selectors = REDDIT_CARD_SELECTORS.join(", ");
    const nodes = guardExecution(() => document.querySelectorAll(selectors), []);

    for (const node of nodes) {
      if (!(node instanceof HTMLElement)) continue;
      const target = getBlockTarget(node);
      if (!(target instanceof HTMLElement)) continue;
      if (seen.has(target)) continue;
      if (!isRedditCandidate(target)) continue;
      seen.add(target);
      posts.push(target);
    }

    return posts;
  }

  function getPostCandidates() {
    if (isStopped) return [];

    if (isYouTubeHost()) {
      return collectYouTubeCandidates();
    }

    if (isRedditHost()) {
      return collectRedditCandidates();
    }

    const seen = new Set();
    const posts = [];

    for (const selector of POST_SELECTORS) {
      const nodes = guardExecution(() => document.querySelectorAll(selector), []);
      for (const node of nodes) {
        if (!(node instanceof HTMLElement)) continue;
        if (seen.has(node)) continue;
        const hasMediaHint = guardExecution(
          () => Boolean(node.querySelector(POST_MEDIA_HINT_SELECTORS.join(", "))),
          false
        );
        if (!hasMediaHint) continue;
        seen.add(node);
        posts.push(node);
      }
    }

    return posts;
  }

  function collectSignals(post) {
    if (isStopped) return "";

    const textParts = [];

    if (post.innerText) {
      textParts.push(post.innerText.slice(0, 2400));
    }

    if (post.textContent) {
      textParts.push(post.textContent.slice(0, 2400));
    }

    textParts.push(post.getAttribute("aria-label") || "");
    textParts.push(post.getAttribute("title") || "");

    if (isRedditHost()) {
      for (const attribute of REDDIT_POST_ATTRIBUTES) {
        textParts.push(post.getAttribute(attribute) || "");
      }
    }

    const metaNodes = guardExecution(
      () => post.querySelectorAll(METADATA_TEXT_SELECTORS.join(", ")),
      []
    );
    for (const node of metaNodes) {
      if (!(node instanceof HTMLElement)) continue;
      textParts.push(node.innerText || "");
      textParts.push(node.textContent || "");
      textParts.push(node.getAttribute("title") || "");
      textParts.push(node.getAttribute("aria-label") || "");
      if (node instanceof HTMLAnchorElement) {
        textParts.push(node.href || "");
      }
    }

    const mediaNodes = guardExecution(() => post.querySelectorAll(MEDIA_SELECTOR), []);
    for (const node of mediaNodes) {
      if (node instanceof HTMLImageElement) {
        textParts.push(node.alt || "");
        textParts.push(node.getAttribute("aria-label") || "");
        textParts.push(node.currentSrc || node.src || "");
      } else if (node instanceof HTMLVideoElement) {
        textParts.push(node.getAttribute("aria-label") || "");
        textParts.push(node.currentSrc || node.src || "");
        if (node.poster) textParts.push(node.poster);
      }
    }

    if (post.shadowRoot) {
      textParts.push(post.shadowRoot.textContent || "");
      const shadowMediaNodes = guardExecution(
        () => post.shadowRoot.querySelectorAll(MEDIA_SELECTOR),
        []
      );
      for (const node of shadowMediaNodes) {
        if (node instanceof HTMLImageElement) {
          textParts.push(node.alt || "");
          textParts.push(node.currentSrc || node.src || "");
        } else if (node instanceof HTMLVideoElement) {
          textParts.push(node.currentSrc || node.src || "");
          if (node.poster) textParts.push(node.poster);
        }
      }
    }

    const youtubeMetadata = getYouTubeNetworkMetadata(post);
    if (youtubeMetadata) {
      textParts.push(youtubeMetadata);
    }

    return normalizeText(textParts.join(" \n "));
  }

  function scorePost(post) {
    const corpus = collectSignals(post);
    if (!corpus) return { score: 0, reasons: [] };

    const reasons = [];
    let score = 0;
    const blockedChannel = isBlockedChannel(post);
    if (blockedChannel) {
      return {
        score: 999,
        reasons: [`blocked-channel:${blockedChannel.label || blockedChannel.key}`]
      };
    }

    for (const keyword of STRONG_KEYWORDS) {
      const normalizedKeyword = normalizeKeyword(keyword);
      if (!normalizedKeyword || !corpus.includes(normalizedKeyword)) continue;
      score += 4;
      reasons.push(normalizedKeyword);
    }

    for (const keyword of WEAK_KEYWORDS) {
      const normalizedKeyword = normalizeKeyword(keyword);
      if (!normalizedKeyword || !corpus.includes(normalizedKeyword)) continue;
      score += 2;
      reasons.push(normalizedKeyword);
    }

    for (const hint of URL_HINTS) {
      const normalizedHint = normalizeKeyword(hint);
      if (!normalizedHint || !corpus.includes(normalizedHint)) continue;
      score += 1;
      reasons.push(`url:${normalizedHint}`);
    }

    if (/\bai\b.{0,18}\b(image|art|video|photo|render)\b/.test(corpus)) {
      score += 3;
      reasons.push("pattern:ai-media");
    }

    if (/\b(created|generated|made|rendered)\b.{0,18}\b(midjourney|dall-e|dalle|stable diffusion|sora|runway|firefly|flux)\b/.test(corpus)) {
      score += 4;
      reasons.push("pattern:model-attribution");
    }

    if (/\bai[\s-]*generated\b/.test(corpus)) {
      score += 4;
      reasons.push("pattern:ai-generated");
    }

    if (/(^|[\s#])ai($|[\s#:|.,!/?_-])/.test(corpus)) {
      score += 2;
      reasons.push("pattern:ai-tag");
    }

    if (/\bai\b.{0,8}\bvideo\b/.test(corpus)) {
      score += 4;
      reasons.push("pattern:ai-video-phrase");
    }

    if (/\b(ai|artificial intelligence)\b.{0,24}\b(video|short|shorts|film|animation|scene)\b/.test(corpus)) {
      score += 3;
      reasons.push("pattern:ai-video");
    }

    if (/(^|[\s#])(midjourney|stablediffusion|stable-diffusion|dalle|sora|runway|firefly|leonardoai)($|[\s#:|.,!/?_-])/.test(corpus)) {
      score += 3;
      reasons.push("pattern:tool-tag");
    }

    return {
      score,
      reasons: Array.from(new Set(reasons)).slice(0, 6)
    };
  }

  function updateStats(hiddenCount) {
    stats = {
      hostname: location.hostname,
      hidden: hiddenCount,
      mode: settings.antiAIMode,
      updatedAt: Date.now()
    };
    safeStorageLocalSet({ [STORAGE_KEYS.stats]: stats });
  }

  function ensureBadge(post, reasons) {
    const target = getBlockTarget(post);
    if (!(target instanceof HTMLElement)) return;

    let badge = target.querySelector(`:scope > .${BADGE_CLASS}`);
    if (!(badge instanceof HTMLElement)) {
      badge = document.createElement("div");
      badge.className = BADGE_CLASS;

      const text = document.createElement("span");
      text.className = "anti-ai-badge-text";
      badge.appendChild(text);

      const button = document.createElement("button");
      button.type = "button";
      button.textContent = "Show";
      button.addEventListener("click", (event) => {
        event.preventDefault();
        event.stopPropagation();
        target.classList.remove(BLUR_CLASS);
        target.setAttribute(REVEALED_ATTR, "1");
        badge.remove();
      });
      badge.appendChild(button);
      target.appendChild(badge);
    }

    const text = badge.querySelector(".anti-ai-badge-text");
    if (text) {
      text.textContent = `antiAI hidden this post: ${reasons.join(", ") || "AI indicators"}`;
    }
  }

  function findYouTubeBlockButtonAnchor(post) {
    if (!(post instanceof HTMLElement) || !isYouTubeHost()) return null;

    const selectors = [
      'a[href^="/@"]',
      'a[href^="/channel/"]',
      'a[href^="/c/"]',
      'a[href^="/user/"]',
      "#channel-name",
      "ytd-channel-name",
      ".shortsLockupViewModelHostOutsideMetadataSubhead",
      ".shortsLockupViewModelHostOutsideMetadataTitle"
    ];

    const anchor = guardExecution(() => post.querySelector(selectors.join(", ")), null);
    return anchor instanceof HTMLElement ? anchor : null;
  }

  function ensureYouTubeBlockButton(post) {
    if (!isYouTubeHost()) return;

    const target = getBlockTarget(post);
    if (!(target instanceof HTMLElement)) return;

    const channel = extractYouTubeChannelInfo(target);
    if (!channel?.key) return;

    const anchor = findYouTubeBlockButtonAnchor(target);
    if (!(anchor instanceof HTMLElement)) return;

    let button = target.querySelector(`.${CHANNEL_BLOCK_BUTTON_CLASS}[data-channel-key="${CSS.escape(channel.key)}"]`);
    if (!(button instanceof HTMLButtonElement)) {
      button = document.createElement("button");
      button.type = "button";
      button.className = CHANNEL_BLOCK_BUTTON_CLASS;
      anchor.insertAdjacentElement("afterend", button);
    }

    button.dataset.channelKey = channel.key;
    button.dataset.channelLabel = channel.label || channel.key;
    button.dataset.channelHref = channel.href || "";
    button.textContent = blockedChannels.has(channel.key) ? "Blocked" : "Block";
    button.disabled = blockedChannels.has(channel.key);
  }

  function applyDecision(post, decision) {
    const target = getBlockTarget(post);
    if (!(target instanceof HTMLElement)) return false;

    target.setAttribute(PROCESSED_ATTR, "1");
    target.setAttribute(SCORE_ATTR, String(decision.score));
    target.setAttribute(REASON_ATTR, decision.reasons.join("|"));

    if (target.getAttribute(REVEALED_ATTR) === "1") {
      target.classList.remove(BLOCK_CLASS, BLUR_CLASS);
      const badge = target.querySelector(`:scope > .${BADGE_CLASS}`);
      if (badge) badge.remove();
      target.removeAttribute(HIDDEN_ATTR);
      return false;
    }

    if (decision.score < getThreshold()) {
      target.classList.remove(BLOCK_CLASS, BLUR_CLASS);
      const badge = target.querySelector(`:scope > .${BADGE_CLASS}`);
      if (badge) badge.remove();
      target.removeAttribute(HIDDEN_ATTR);
      target.removeAttribute(SKIPPED_ATTR);
      target.removeAttribute(REVEALED_ATTR);
      return false;
    }

    if (isYouTubeShortsPage()) {
      return skipYouTubeShort(target);
    }

    target.setAttribute(HIDDEN_ATTR, "1");
    if (settings.antiAIMode === "blur") {
      target.classList.remove(BLOCK_CLASS);
      if (getComputedStyle(target).position === "static") {
        target.style.position = "relative";
      }
      target.classList.add(BLUR_CLASS);
      ensureBadge(target, decision.reasons);
    } else {
      target.classList.remove(BLUR_CLASS);
      const badge = target.querySelector(`:scope > .${BADGE_CLASS}`);
      if (badge) badge.remove();
      target.classList.add(BLOCK_CLASS);
    }

    return true;
  }

  function scanFeed() {
    if (isStopped) return;

    const aiOverviewHidden = removeSearchEngineAiOverviews();

    if (!settings.antiAIEnabled) {
      const processedNodes = guardExecution(
        () => document.querySelectorAll(`[${PROCESSED_ATTR}="1"]`),
        []
      );
      for (const node of processedNodes) {
        if (!(node instanceof HTMLElement)) continue;
        node.classList.remove(BLOCK_CLASS, BLUR_CLASS);
        node.removeAttribute(HIDDEN_ATTR);
        const badge = node.querySelector(`:scope > .${BADGE_CLASS}`);
        if (badge) badge.remove();
      }
      updateStats(aiOverviewHidden);
      return;
    }

    const posts = getPostCandidates();
    let hidden = 0;

    for (const post of posts) {
      ensureYouTubeBlockButton(post);
      const decision = scorePost(post);
      if (applyDecision(post, decision)) {
        hidden += 1;
      }
    }

    updateStats(hidden + aiOverviewHidden);
  }

  function scheduleScan() {
    if (isStopped) return;

    window.clearTimeout(scanTimer);
    scanTimer = window.setTimeout(() => {
      guardExecution(() => {
        scanFeed();
      });
    }, 150);
  }

  function loadSettings(callback) {
    safeStorageSyncGet(
      {
        ...DEFAULT_SETTINGS,
        [STORAGE_KEYS.blockedChannels]: []
      },
      (items) => {
      settings = {
        antiAIEnabled: Boolean(items[STORAGE_KEYS.enabled]),
        antiAIMode: items[STORAGE_KEYS.mode] === "blur" ? "blur" : "remove",
        antiAISensitivity: items[STORAGE_KEYS.sensitivity] === "strict" ? "strict" : "normal",
        antiAIHideAiOverview: Boolean(items[STORAGE_KEYS.hideAiOverview])
      };
        blockedChannels.clear();
        const storedChannels = Array.isArray(items[STORAGE_KEYS.blockedChannels])
          ? items[STORAGE_KEYS.blockedChannels]
          : [];
        for (const item of storedChannels) {
          const key = normalizeText(item?.key || "");
          if (!key) continue;
          blockedChannels.set(key, {
            key,
            label: normalizeText(item?.label || key),
            href: String(item?.href || "")
          });
        }
      callback();
      }
    );
  }

  function bindMessageBridge() {
    window.addEventListener("message", (event) => {
      if (isStopped) return;
      if (event.source !== window) return;

      const message = event.data;
      if (!message || message.source !== BRIDGE_SOURCE) return;
      if (message.kind !== "youtube-metadata" || !Array.isArray(message.items)) return;

      let changed = false;
      for (const item of message.items) {
        const videoId = String(item?.videoId || "").trim();
        const text = normalizeText(item?.text || "");
        if (!videoId || !text) continue;
        const previous = youtubeMetadataByVideoId.get(videoId) || "";
        if (previous.includes(text)) continue;
        youtubeMetadataByVideoId.set(videoId, `${previous} ${text}`.trim());
        changed = true;
      }

      if (changed) {
        scheduleScan();
      }
    });
  }

  function injectHook() {
    if (!isYouTubeHost()) return;
    if (document.getElementById("anti-ai-page-hook")) return;

    const script = document.createElement("script");
    script.id = "anti-ai-page-hook";
    script.src = chrome.runtime.getURL("page-hook.js");
    script.async = false;
    script.onload = () => script.remove();
    (document.head || document.documentElement).appendChild(script);
  }

  function bindStorageChanges() {
    safeBindStorageChanges((changes, area) => {
      if (area !== "sync") return;
      let changed = false;

      if (changes[STORAGE_KEYS.enabled]) {
        settings.antiAIEnabled = Boolean(changes[STORAGE_KEYS.enabled].newValue);
        changed = true;
      }

      if (changes[STORAGE_KEYS.mode]) {
        settings.antiAIMode = changes[STORAGE_KEYS.mode].newValue === "blur" ? "blur" : "remove";
        changed = true;
      }

      if (changes[STORAGE_KEYS.sensitivity]) {
        settings.antiAISensitivity =
          changes[STORAGE_KEYS.sensitivity].newValue === "strict" ? "strict" : "normal";
        changed = true;
      }

      if (changes[STORAGE_KEYS.hideAiOverview]) {
        settings.antiAIHideAiOverview = Boolean(changes[STORAGE_KEYS.hideAiOverview].newValue);
        changed = true;
      }

      if (changes[STORAGE_KEYS.blockedChannels]) {
        blockedChannels.clear();
        const nextChannels = Array.isArray(changes[STORAGE_KEYS.blockedChannels].newValue)
          ? changes[STORAGE_KEYS.blockedChannels].newValue
          : [];
        for (const item of nextChannels) {
          const key = normalizeText(item?.key || "");
          if (!key) continue;
          blockedChannels.set(key, {
            key,
            label: normalizeText(item?.label || key),
            href: String(item?.href || "")
          });
        }
        changed = true;
      }

      if (changed) {
        scheduleScan();
      }
    });
  }

  function persistBlockedChannels() {
    safeStorageSyncSet({
      [STORAGE_KEYS.blockedChannels]: Array.from(blockedChannels.values())
    });
  }

  function bindChannelBlockClicks() {
    document.addEventListener("click", (event) => {
      if (isStopped) return;
      const target = event.target;
      if (!(target instanceof Element)) return;
      const button = target.closest(`.${CHANNEL_BLOCK_BUTTON_CLASS}`);
      if (!(button instanceof HTMLButtonElement)) return;

      event.preventDefault();
      event.stopPropagation();

      const key = normalizeText(button.dataset.channelKey || "");
      if (!key) return;

      blockedChannels.set(key, {
        key,
        label: normalizeText(button.dataset.channelLabel || key),
        href: String(button.dataset.channelHref || "")
      });
      persistBlockedChannels();
      scheduleScan();
    });
  }

  function startObserver() {
    if (isStopped) return;

    observer = new MutationObserver(() => {
      guardExecution(() => {
        scheduleScan();
      });
    });

    guardExecution(() => {
      observer.observe(document.documentElement, {
        childList: true,
        subtree: true
      });
    });
  }

  function init() {
    installStyles();
    bindMessageBridge();
    bindChannelBlockClicks();
    bindStorageChanges();
    loadSettings(() => {
      injectHook();
      scanFeed();
      startObserver();
    });
  }

  init();
})();
